const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{chat: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{messenger: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{cooper: 0},
	{Solid: 0},
	{platform: 0},
	{background: 0},
	{flag: 0},
	{tripwire: 0},
	{yellowText: 0},
	{whereIsTheLevel: 0},
	{jump: 0},
	{Sine: 0},
	{enemy: 0},
	{glitch: 0},
	{Fade: 0},
	{Text: 0},
	{Sprite: 0},
	{gameover: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Sprite2: 0},
	{button: 0}
];

self.InstanceType = {
	chat: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	messenger: class extends self.ITextInputInstance {},
	cooper: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	background: class extends self.ITiledBackgroundInstance {},
	flag: class extends self.ISpriteInstance {},
	tripwire: class extends self.ISpriteInstance {},
	yellowText: class extends self.ITextInstance {},
	whereIsTheLevel: class extends self.ITextInstance {},
	jump: class extends self.ITextInstance {},
	enemy: class extends self.ISpriteInstance {},
	glitch: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	gameover: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {}
}