const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{startingcell: 0},
	{bucket: 0},
	{teddyBear: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{key: 0},
	{LocalStorage: 0},
	{Inventory: 0},
	{InventoryFrame: 0},
	{lock: 0},
	{torch: 0},
	{circusTent: 0},
	{circusBall: 0},
	{bellaby: 0},
	{table: 0},
	{circusTentred: 0},
	{teddytext: 0},
	{keyText: 0},
	{buckettext: 0},
	{startcelltext: 0},
	{torchtext: 0},
	{circusballtext: 0},
	{bellabytext: 0},
	{teddytext2: 0},
	{startcircustext: 0},
	{hallway: 0},
	{arrow: 0},
	{stairwayDoor: 0},
	{doortextattic: 0},
	{atticbackground: 0},
	{hallwaytext: 0},
	{gardendoortext: 0},
	{gardendoor: 0},
	{stairway: 0},
	{atticdoor: 0},
	{walkinstairway: 0},
	{pickuplinesstairway: 0},
	{coinputdown: 0},
	{openstairwaydoortext: 0},
	{book: 0},
	{well: 0},
	{coin: 0},
	{aquarium: 0},
	{aquariumDoor: 0},
	{tank: 0},
	{aquariumentertext: 0},
	{cointext: 0},
	{emptytanktext: 0},
	{enterattictext: 0},
	{putdowncircusballtext: 0},
	{circusballclick: 0},
	{circusball2: 0},
	{arrow2: 0},
	{teddyclick: 0},
	{playbutton: 0},
	{TiledBackground: 0},
	{logo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{theEnd: 0},
	{arrow3: 0},
	{TEDDYBEAR_ID: 0},
	{BELLABY_ID: 0},
	{KEY_ID: 0},
	{CIRCUSBALL_ID: 0},
	{BUCKET_ID: 0},
	{COIN_ID: 0},
	{BOOK_ID: 0},
	{completed_aquarium: 0},
	{completed_stairway: 0},
	{completed_attic: 0},
	{Circus_room_completed: 0},
	{cell_completed: 0},
	{objectID: 0},
	{lookforID: 0}
];

self.InstanceType = {
	startingcell: class extends self.ISpriteInstance {},
	bucket: class extends self.ISpriteInstance {},
	teddyBear: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	key: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Inventory: class extends self.IArrayInstance {},
	InventoryFrame: class extends self.ISpriteInstance {},
	lock: class extends self.ISpriteInstance {},
	torch: class extends self.ISpriteInstance {},
	circusTent: class extends self.ISpriteInstance {},
	circusBall: class extends self.ISpriteInstance {},
	bellaby: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	circusTentred: class extends self.ISpriteInstance {},
	teddytext: class extends self.ITextInstance {},
	keyText: class extends self.ITextInstance {},
	buckettext: class extends self.ITextInstance {},
	startcelltext: class extends self.ITextInstance {},
	torchtext: class extends self.ITextInstance {},
	circusballtext: class extends self.ITextInstance {},
	bellabytext: class extends self.ITextInstance {},
	teddytext2: class extends self.ITextInstance {},
	startcircustext: class extends self.ITextInstance {},
	hallway: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	stairwayDoor: class extends self.ISpriteInstance {},
	doortextattic: class extends self.ITextInstance {},
	atticbackground: class extends self.ISpriteInstance {},
	hallwaytext: class extends self.ITextInstance {},
	gardendoortext: class extends self.ITextInstance {},
	gardendoor: class extends self.ISpriteInstance {},
	stairway: class extends self.ISpriteInstance {},
	atticdoor: class extends self.ISpriteInstance {},
	walkinstairway: class extends self.ITextInstance {},
	pickuplinesstairway: class extends self.ITextInstance {},
	coinputdown: class extends self.ITextInstance {},
	openstairwaydoortext: class extends self.ITextInstance {},
	book: class extends self.ISpriteInstance {},
	well: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	aquarium: class extends self.ISpriteInstance {},
	aquariumDoor: class extends self.ISpriteInstance {},
	tank: class extends self.ISpriteInstance {},
	aquariumentertext: class extends self.ITextInstance {},
	cointext: class extends self.ITextInstance {},
	emptytanktext: class extends self.ITextInstance {},
	enterattictext: class extends self.ITextInstance {},
	putdowncircusballtext: class extends self.ITextInstance {},
	circusballclick: class extends self.ISpriteInstance {},
	circusball2: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	teddyclick: class extends self.ISpriteInstance {},
	playbutton: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	theEnd: class extends self.ITextInstance {},
	arrow3: class extends self.ISpriteInstance {}
}